services:
  # Frontend - Next.js Application
  - type: web
    name: podrec-frontend
    runtime: node
    plan: starter # You can upgrade to standard or pro as needed
    region: oregon # Choose your preferred region
    rootDir: ./frontend
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: NEXT_PUBLIC_API_URL
        value: https://podrec-backend.onrender.com/api # Update with your backend URL
      - key: NEXT_PUBLIC_SOCKET_URL
        value: https://podrec-backend.onrender.com # Update with your backend URL
      
  # Backend - Express API Server
  - type: web
    name: podrec-backend
    runtime: node
    plan: starter # You can upgrade to standard or pro as needed
    region: oregon
    rootDir: ./backend
    buildCommand: npm install && npm run build && npx prisma generate && npx prisma migrate deploy
    startCommand: npm start
    healthCheckPath: /api
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        value: # Your Neon DB connection string - set this in Render dashboard
      - key: REDIS_URL
        value: # Your Upstash Redis URL - set this in Render dashboard
      - key: JWT_SECRET
        generateValue: true # Render will generate a secure random value
      - key: PORT
        value: 8080
      - key: CLOUDINARY_CLOUD_NAME
        value: # Set this in Render dashboard
      - key: CLOUDINARY_API_KEY
        value: # Set this in Render dashboard
      - key: CLOUDINARY_API_SECRET
        value: # Set this in Render dashboard
    
  # Background Worker Service for Video Processing
  - type: worker
    name: podrec-worker
    runtime: node
    plan: starter
    region: oregon
    rootDir: ./backend
    buildCommand: npm install && npm run build && npx prisma generate
    startCommand: npm run start:worker
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        value: # Your Neon DB connection string - set this in Render dashboard
      - key: REDIS_URL
        value: # Your Upstash Redis URL - set this in Render dashboard
      - key: CLOUDINARY_CLOUD_NAME
        value: # Set this in Render dashboard
      - key: CLOUDINARY_API_KEY
        value: # Set this in Render dashboard
      - key: CLOUDINARY_API_SECRET
        value: # Set this in Render dashboard

# Note: Using external Neon DB - no internal database configuration needed
